const DINOS = [
  {
    name: "Tyrannosaurus",
    common: "T-Rex",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Tyrannosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 12,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/trex.jpg",
    imgPhoto: "imgphoto/trex2.webp",
  },
  {
    name: "Tarbosaurus",
    common: "Tarbossauro",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Tyrannosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 10,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/tarbo2.webp",
    imgPhoto: "imgphoto/tarbo.webp",
  },
  {
    name: "Velociraptor",
    common: "Velociraptor",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Dromaeosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 2,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/velociraptor.webp",
    imgPhoto: "imgphoto/velociraptor2.webp",  },
  {
    name: "Deinonychus",
    common: "Deinônique",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Dromaeosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 3,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/Deinonychus.png",
    imgPhoto: "imgphoto/Deinonychus2.webp",
  },
  {
    name: "Utahraptor",
    common: "Utarraptor",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Dromaeosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 6,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/Utahraptor.webp",
    imgPhoto: "imgphoto/utharaptor2.jpg",
  },
  {
    name: "Microraptor",
    common: "Microrraptor",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Dromaeosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 1,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/microraptor2.webp",
    imgPhoto: "imgphoto/microraptor.jpg",
  },
  {
    name: "Oviraptor",
    common: "Ladrão de Ovos",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Oviraptoridae"],
    period: "Cretáceo",
    diet: "Onívoro",
    size: 2,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/oviraptor.webp",
    imgPhoto: "imgphoto/Oviraptor2.jpg",
  },
  {
    name: "Troodon",
    common: "Troodonte",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Troodontidae"],
    period: "Cretáceo",
    diet: "Onívoro",
    size: 2,
    loco: "Bípede",
    region: "América do Norte",
   imgClassic: "img/trodonte.jpg",
    imgPhoto: "imgphoto/trodonte2.webp",
  },
  {
    name: "Gallimimus",
    common: "Galimimim",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Ornithomimidae"],
    period: "Cretáceo",
    diet: "Onívoro",
    size: 6,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/galimimus.webp",
    imgPhoto: "imgphoto/gallimimus2.webp",
  },
  {
    name: "Therizinosaurus",
    common: "Terizinossauro",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Therizinosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 10,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/Therizinosaurus2.png",
    imgPhoto: "imgphoto/Therizinosaurus.webp",
  },
  {
    name: "Compsognathus",
    common: "Compso",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Compsognathidae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 1,
    loco: "Bípede",
    region: "Europa",
    imgClassic: "img/compsognathus.png",
    imgPhoto: "imgphoto/Compsognathus2.jpg",
  },
  {
    name: "Spinosaurus",
    common: "Espinhossauro",
    path: ["Saurischia", "Theropoda", "Spinosauria", "Spinosauridae"],
    period: "Cretáceo",
    diet: "Piscívoro",
    size: 14,
    loco: "Bípede",
    region: "África",
    imgClassic: "img/espinossauro2.webp",
    imgPhoto: "imgphoto/espinossauro.jpg",
  },
  {
    name: "Baryonyx",
    common: "Barionique",
    path: ["Saurischia", "Theropoda", "Spinosauria", "Spinosauridae"],
    period: "Cretáceo",
    diet: "Piscívoro",
    size: 9,
    loco: "Bípede",
    region: "Europa",
    imgClassic: "img/barionix.webp",
    imgPhoto: "imgphoto/barionix2.jpg",
  },
  {
    name: "Suchomimus",
    common: "Sucômimo",
    path: ["Saurischia", "Theropoda", "Spinosauria", "Spinosauridae"],
    period: "Cretáceo",
    diet: "Piscívoro",
    size: 11,
    loco: "Bípede",
    region: "África",
    imgClassic: "img/sochomimus.webp",
    imgPhoto: "imgphoto/suchomimus2.webp",
  },
  {
    name: "Allosaurus",
    common: "Alossauro",
    path: ["Saurischia", "Theropoda", "Carnosauria", "Allosauridae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 9,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/alossauro.jpg",
    imgPhoto: "imgphoto/alossauro2.jpg",
  },
  {
    name: "Giganotosaurus",
    common: "Giganoto",
    path: ["Saurischia", "Theropoda", "Carnosauria", "Carcharodontosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 13,
    loco: "Bípede",
    region: "América do Sul",
    imgClassic: "img/gigantossauro.webp",
    imgPhoto: "imgphoto/gigantossauro2.webp",
  },
  {
    name: "Carcharodontosaurus",
    common: "Carcarodonto",
    path: ["Saurischia", "Theropoda", "Carnosauria", "Carcharodontosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 13,
    loco: "Bípede",
    region: "África",
    imgClassic: "img/carcadonte.webp",
    imgPhoto: "imgphoto/carcadonte2.jpg",
  },
  {
    name: "Carnotaurus",
    common: "Touro Carnívoro",
    path: ["Saurischia", "Theropoda", "Ceratosauria", "Abelisauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 8,
    loco: "Bípede",
    region: "América do Sul",
    imgClassic: "img/carnotauro.webp",
    imgPhoto: "imgphoto/carnotauro2.jpg",
  },
  {
    name: "Ceratosaurus",
    common: "Ceratossauro",
    path: ["Saurischia", "Theropoda", "Ceratosauria", "Ceratosauridae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 6,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/ceratossauro.webp",
    imgPhoto: "imgphoto/ceratossauro2.webp",
  },
  {
    name: "Abelisaurus",
    common: "Abelissauro",
    path: ["Saurischia", "Theropoda", "Ceratosauria", "Abelisauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 7,
    loco: "Bípede",
    region: "América do Sul",
    imgClassic: "img/Abelissauro.jpg",
    imgPhoto: "imgphoto/abelissauro2.webp",
  },
  {
    name: "Megalosaurus",
    common: "Megalossauro",
    path: ["Saurischia", "Theropoda", "Megalosauria", "Megalosauridae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 6,
    loco: "Bípede",
    region: "Europa",
    imgClassic: "img/megalossauro.png",
    imgPhoto: "imgphoto/megalossauro2.webp",
  },
  {
    name: "Dilophosaurus",
    common: "Dilofo",
    path: ["Saurischia", "Theropoda", "Coelophysoidea", "Dilophosauridae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 6,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/dilophosauro.webp",
    imgPhoto: "imgphoto/dilophosauro2.jpg",
  },
  {
    name: "Coelophysis",
    common: "Celófise",
    path: ["Saurischia", "Theropoda", "Coelophysoidea", "Coelophysidae"],
    period: "Triássico",
    diet: "Carnívoro",
    size: 3,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/coelophysys.webp",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Brontosaurus",
    common: "Brontossauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Diplodocidae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 22,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/coelophysys.webp",
    imgPhoto: "imgphoto/coelophysys2.webp",
  },
  {
    name: "Diplodocus",
    common: "Diplodoco",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Diplodocidae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 27,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/diplodoco2.png",
    imgPhoto: "imgphoto/diplodoco.webp",
  },
  {
    name: "Apatosaurus",
    common: "Apatossauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Diplodocidae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 23,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/apatossauro.webp",
    imgPhoto: "imgphoto/Apatosaurus2.jpg",
  },
  {
    name: "Amargasaurus",
    common: "Amargassauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Dicraeosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Quadrúpede",
    region: "América do Sul",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/amargossauro2.webp",
  },
  {
    name: "Brachiosaurus",
    common: "Braquiossauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Brachiosauridae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 26,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Mamenchisaurus",
    common: "Mamenchissauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Mamenchisauridae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 25,
    loco: "Quadrúpede",
    region: "Ásia",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Argentinosaurus",
    common: "Argentinossauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Titanosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 35,
    loco: "Quadrúpede",
    region: "América do Sul",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Patagotitan",
    common: "Patagotitã",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Titanosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 37,
    loco: "Quadrúpede",
    region: "América do Sul",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Dreadnoughtus",
    common: "Dreadnoughtus",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Titanosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 26,
    loco: "Quadrúpede",
    region: "América do Sul",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Stegosaurus",
    common: "Estegossauro",
    path: ["Ornithischia", "Thyreophora", "Stegosauria", "Stegosauridae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 9,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Kentrosaurus",
    common: "Kentrossauro",
    path: ["Ornithischia", "Thyreophora", "Stegosauria", "Stegosauridae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 5,
    loco: "Quadrúpede",
    region: "África",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Ankylosaurus",
    common: "Anquilossauro",
    path: ["Ornithischia", "Thyreophora", "Ankylosauria", "Ankylosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 10,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Euoplocephalus",
    common: "Euoplocefalus",
    path: ["Ornithischia", "Thyreophora", "Ankylosauria", "Ankylosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 6,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Nodosaurus",
    common: "Nodossauro",
    path: ["Ornithischia", "Thyreophora", "Ankylosauria", "Nodosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 4,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Parasaurolophus",
    common: "Parasaurolofus",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 10,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Edmontosaurus",
    common: "Edmontossauro",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 13,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Maiasaura",
    common: "Maiassaura",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Corythosaurus",
    common: "Corintossauro",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Lambeosaurus",
    common: "Lambêossauro",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Iguanodon",
    common: "Iguanodonte",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Iguanodontidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 10,
    loco: "Ambos",
    region: "Europa",
    imgClassic: "img/iguanodonte.webp",
    imgPhoto: "imgphoto/inguanodon2.jpg",
  },
  {
    name: "Triceratops",
    common: "Tricerátops",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Styracosaurus",
    common: "Estiracossauro",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 6,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Pentaceratops",
    common: "Pentacerátops",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 8,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Torosaurus",
    common: "Toraussauro",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Pachyrhinosaurus",
    common: "Paquirinossauro",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 8,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Protoceratops",
    common: "Protocerátops",
    path: [
      "Ornithischia",
      "Marginocephalia",
      "Ceratopsia",
      "Protoceratopsidae",
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 2,
    loco: "Quadrúpede",
    region: "Ásia",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Psittacosaurus",
    common: "Papagaiossauro",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Psittacosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 2,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Pachycephalosaurus",
    common: "Cabeção",
    path: [
      "Ornithischia",
      "Marginocephalia",
      "Pachycephalosauria",
      "Pachycephalosauridae",
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 5,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Stygimoloch",
    common: "Estigimoloque",
    path: [
      "Ornithischia",
      "Marginocephalia",
      "Pachycephalosauria",
      "Pachycephalosauridae",
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 3,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/trex.png",
    imgPhoto: "imgphoto/trex2.jpg",
  },
];
