const DINOS = [
  {
    name: "Tyrannosaurus",
    common: "T-Rex",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Tyrannosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 12,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/trex.jpg",
    imgPhoto: "imgphoto/trex2.webp",
  },
  {
    name: "Tarbosaurus",
    common: "Tarbossauro",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Tyrannosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 10,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/tarbo2.webp",
    imgPhoto: "imgphoto/tarbo.webp",
  },
  {
    name: "Velociraptor",
    common: "Velociraptor",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Dromaeosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 2,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/velociraptor.webp",
    imgPhoto: "imgphoto/velociraptor2.webp",  },
  {
    name: "Deinonychus",
    common: "Deinonico",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Dromaeosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 3,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/Deinonychus.png",
    imgPhoto: "imgphoto/Deinonychus2.webp",
  },
  {
    name: "Utahraptor",
    common: "Utarraptor",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Dromaeosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 6,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/Utahraptor.webp",
    imgPhoto: "imgphoto/utharaptor2.jpg",
  },
  {
    name: "Microraptor",
    common: "Microrraptor",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Dromaeosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 1,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/microraptor2.webp",
    imgPhoto: "imgphoto/microraptor.jpg",
  },
  {
    name: "Oviraptor",
    common: "Oviraptor",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Oviraptoridae"],
    period: "Cretáceo",
    diet: "Onívoro",
    size: 2,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/oviraptor.webp",
    imgPhoto: "imgphoto/Oviraptor2.jpg",
  },
  {
    name: "Troodon",
    common: "Troodonte",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Troodontidae"],
    period: "Cretáceo",
    diet: "Onívoro",
    size: 2,
    loco: "Bípede",
    region: "América do Norte",
   imgClassic: "img/trodonte.jpg",
    imgPhoto: "imgphoto/trodonte2.webp",
  },
  {
    name: "Gallimimus",
    common: "Galimimus",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Ornithomimidae"],
    period: "Cretáceo",
    diet: "Onívoro",
    size: 6,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/galimimus.webp",
    imgPhoto: "imgphoto/gallimimus2.webp",
  },
  {
    name: "Therizinosaurus",
    common: "Terizinossauro",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Therizinosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 10,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/Therizinosaurus2.png",
    imgPhoto: "imgphoto/Therizinosaurus.webp",
  },
  {
    name: "Compsognathus",
    common: "Compsognathus",
    path: ["Saurischia", "Theropoda", "Coelurosauria", "Compsognathidae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 1,
    loco: "Bípede",
    region: "Europa",
    imgClassic: "img/compsognathus.png",
    imgPhoto: "imgphoto/Compsognathus2.jpg",
  },
  {
    name: "Spinosaurus",
    common: "Espinossauro",
    path: ["Saurischia", "Theropoda", "Spinosauria", "Spinosauridae"],
    period: "Cretáceo",
    diet: "Piscívoro",
    size: 14,
    loco: "Bípede",
    region: "África",
    imgClassic: "img/espinossauro2.webp",
    imgPhoto: "imgphoto/espinossauro.jpg",
  },
  {
    name: "Baryonyx",
    common: "Barionique",
    path: ["Saurischia", "Theropoda", "Spinosauria", "Spinosauridae"],
    period: "Cretáceo",
    diet: "Piscívoro",
    size: 9,
    loco: "Bípede",
    region: "Europa",
    imgClassic: "img/barionix.webp",
    imgPhoto: "imgphoto/barionix2.jpg",
  },
  {
    name: "Suchomimus",
    common: "Sucômimo",
    path: ["Saurischia", "Theropoda", "Spinosauria", "Spinosauridae"],
    period: "Cretáceo",
    diet: "Piscívoro",
    size: 11,
    loco: "Bípede",
    region: "África",
    imgClassic: "img/sochomimus.webp",
    imgPhoto: "imgphoto/suchomimus2.webp",
  },
  {
    name: "Allosaurus",
    common: "Alossauro",
    path: ["Saurischia", "Theropoda", "Carnosauria", "Allosauridae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 9,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/alossauro.jpg",
    imgPhoto: "imgphoto/alossauro2.jpg",
  },
  {
    name: "Giganotosaurus",
    common: "Giganoto",
    path: ["Saurischia", "Theropoda", "Carnosauria", "Carcharodontosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 13,
    loco: "Bípede",
    region: "América do Sul",
    imgClassic: "img/gigantossauro.webp",
    imgPhoto: "imgphoto/gigantossauro2.webp",
  },
  {
    name: "Carcharodontosaurus",
    common: "Carcarodonto",
    path: ["Saurischia", "Theropoda", "Carnosauria", "Carcharodontosauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 13,
    loco: "Bípede",
    region: "África",
    imgClassic: "img/carcadonte.webp",
    imgPhoto: "imgphoto/carcadonte2.jpg",
  },
  {
    name: "Carnotaurus",
    common: "Carnotauro",
    path: ["Saurischia", "Theropoda", "Ceratosauria", "Abelisauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 8,
    loco: "Bípede",
    region: "América do Sul",
    imgClassic: "img/carnotauro.webp",
    imgPhoto: "imgphoto/carnotauro2.jpg",
  },
  {
    name: "Ceratosaurus",
    common: "Ceratossauro",
    path: ["Saurischia", "Theropoda", "Ceratosauria", "Ceratosauridae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 6,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/ceratossauro.webp",
    imgPhoto: "imgphoto/ceratossauro2.webp",
  },
  {
    name: "Abelisaurus",
    common: "Abelissauro",
    path: ["Saurischia", "Theropoda", "Ceratosauria", "Abelisauridae"],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 7,
    loco: "Bípede",
    region: "América do Sul",
    imgClassic: "img/Abelissauro.jpg",
    imgPhoto: "imgphoto/abelissauro2.webp",
  },
  {
    name: "Megalosaurus",
    common: "Megalossauro",
    path: ["Saurischia", "Theropoda", "Megalosauria", "Megalosauridae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 6,
    loco: "Bípede",
    region: "Europa",
    imgClassic: "img/megalossauro.png",
    imgPhoto: "imgphoto/megalossauro2.webp",
  },
  {
    name: "Dilophosaurus",
    common: "Dilofossauro",
    path: ["Saurischia", "Theropoda", "Coelophysoidea", "Dilophosauridae"],
    period: "Jurássico",
    diet: "Carnívoro",
    size: 6,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/dilophosauro.webp",
    imgPhoto: "imgphoto/dilophosauro2.jpg",
  },
  {
    name: "Coelophysis",
    common: "Celófise",
    path: ["Saurischia", "Theropoda", "Coelophysoidea", "Coelophysidae"],
    period: "Triássico",
    diet: "Carnívoro",
    size: 3,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/coelophysys.webp",
    imgPhoto: "imgphoto/trex2.jpg",
  },
  {
    name: "Brontosaurus",
    common: "Brontossauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Diplodocidae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 22,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/coelophysys.webp",
    imgPhoto: "imgphoto/coelophysys2.webp",
  },
  {
    name: "Diplodocus",
    common: "Diplodoco",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Diplodocidae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 27,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/diplodoco2.png",
    imgPhoto: "imgphoto/diplodoco.webp",
  },
  {
    name: "Apatosaurus",
    common: "Apatossauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Diplodocidae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 23,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/apatossauro.webp",
    imgPhoto: "imgphoto/Apatosaurus2.jpg",
  },
  {
    name: "Amargasaurus",
    common: "Amargassauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Dicraeosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Quadrúpede",
    region: "América do Sul",
    imgClassic: "img/Amargasaurus.jpg",
    imgPhoto: "imgphoto/amargossauro2.webp",
  },
  {
    name: "Brachiosaurus",
    common: "Braquiossauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Brachiosauridae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 26,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/braquiossauro.webp",
    imgPhoto: "imgphoto/braquiossauro2.jpg",
  },
  {
    name: "Mamenchisaurus",
    common: "Mamenchissauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Mamenchisauridae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 25,
    loco: "Quadrúpede",
    region: "Ásia",
    imgClassic: "img/mamenchissauro.jpg",
    imgPhoto: "imgphoto/mamenchissauro2.jpg",
  },
  {
    name: "Argentinosaurus",
    common: "Argentinossauro",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Titanosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 35,
    loco: "Quadrúpede",
    region: "América do Sul",
    imgClassic: "img/argentinossauro.jpg",
    imgPhoto: "imgphoto/argentinossauro2.jpg",
  },
  {
    name: "Patagotitan",
    common: "Patagotitã",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Titanosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 37,
    loco: "Quadrúpede",
    region: "América do Sul",
    imgClassic:"img/patagotitan.webp",
    imgPhoto: "imgphoto/patagotitan2.webp",
  },
  {
    name: "Dreadnoughtus",
    common: "Dreadnoughtus",
    path: ["Saurischia", "Sauropodomorpha", "Sauropoda", "Titanosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 26,
    loco: "Quadrúpede",
    region: "América do Sul",
    imgClassic:"img/dreadnoughts.webp",
    imgPhoto: "imgphoto/Dreadnoughtus2.jpg",
  },
  {
    name: "Stegosaurus",
    common: "Estegossauro",
    path: ["Ornithischia", "Thyreophora", "Stegosauria", "Stegosauridae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 9,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/stegossauro.webp",
    imgPhoto:"imgphoto/estegossauro2.jpg",
  },
  {
    name: "Kentrosaurus",
    common: "Kentrossauro",
    path: ["Ornithischia", "Thyreophora", "Stegosauria", "Stegosauridae"],
    period: "Jurássico",
    diet: "Herbívoro",
    size: 5,
    loco: "Quadrúpede",
    region: "África",
    imgClassic:"img/kentrosaurus.jpg",
    imgPhoto: "imgphoto/kentrosauro2.webp",
  },
  {
    name: "Ankylosaurus",
    common: "Anquilossauro",
    path: ["Ornithischia", "Thyreophora", "Ankylosauria", "Ankylosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 10,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic:"img/anquilossauro.webp",
    imgPhoto: "imgphoto/anquilossauro2.webp",
  },
  {
    name: "Euoplocephalus",
    common: "Euoplocefalus",
    path: ["Ornithischia", "Thyreophora", "Ankylosauria", "Ankylosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 6,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic:"img/euoplocephalus.png",
    imgPhoto: "imgphoto/Euoplocéfalo2.jpg",
  },
  {
    name: "Nodosaurus",
    common: "Nodossauro",
    path: ["Ornithischia", "Thyreophora", "Ankylosauria", "Nodosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 4,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/Nodosaurus.webp",
    imgPhoto: "imgphoto/nodosauro2.jpg",
  },
  {
    name: "Parasaurolophus",
    common: "Parasaurolofus",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 10,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/parasaurolophus.jpg",
    imgPhoto: "imgphoto/Parasaurolophus2.jpg",
  },
  {
    name: "Edmontosaurus",
    common: "Edmontossauro",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 13,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/edmontosauro.webp",
    imgPhoto: "iimgphoto/edmontosauro2.jpg",
  },
  {
    name: "Maiasaura",
    common: "Maiassaura",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/maiasaura.jpg",
    imgPhoto: "imgphoto/maiasaura2.jpg",
  },
  {
    name: "Corythosaurus",
    common: "Corintossauro",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/corythosaurus.webp",
    imgPhoto: "imgphoto/Corythosaurus2.jpg",
  },
  {
    name: "Lambeosaurus",
    common: "Lambêossauro",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Hadrosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Ambos",
    region: "América do Norte",
    imgClassic: "img/lambeosaurus.webp",
    imgPhoto: "imgphoto/Lambeosaurus2.jpg",
  },
  {
    name: "Iguanodon",
    common: "Iguanodonte",
    path: ["Ornithischia", "Ornithopoda", "Iguanodontia", "Iguanodontidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 10,
    loco: "Ambos",
    region: "Europa",
    imgClassic: "img/iguanodonte.webp",
    imgPhoto: "imgphoto/inguanodon2.jpg",
  },
  {
    name: "Triceratops",
    common: "Tricerátops",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/triceratops.jpg",
    imgPhoto: "imgphoto/triceratops2.jpg",
  },
  {
    name: "Styracosaurus",
    common: "Estiracossauro",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 6,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/styracosaurus.webp",
    imgPhoto: "imgphoto/Styracosaurus2.jpg",
  },
  {
    name: "Pentaceratops",
    common: "Pentacerátops",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 8,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/Pentaceratops.jpg",
    imgPhoto: "imgphoto/pentaceratops2.jpg",
  },
  {
    name: "Torosaurus",
    common: "Toraussauro",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 9,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/Torosaurus.jpg",
    imgPhoto: "imgphoto/torosaurus2.jpg",
  },
  {
    name: "Pachyrhinosaurus",
    common: "Paquirinossauro",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 8,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/Pachyrhinosaurus.webp",
    imgPhoto: "imgphoto/pachyrhinsaurus2.webp",
  },
  {
    name: "Protoceratops",
    common: "Protocerátops",
    path: [
      "Ornithischia",
      "Marginocephalia",
      "Ceratopsia",
      "Protoceratopsidae",
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 2,
    loco: "Quadrúpede",
    region: "Ásia",
    imgClassic: "img/Protoceratops.jpg",
    imgPhoto: "imgphoto/protoceratops2.webp",
  },
  {
    name: "Psittacosaurus",
    common: "Psitaco",
    path: ["Ornithischia", "Marginocephalia", "Ceratopsia", "Psittacosauridae"],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 2,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/psitaco.jpg",
    imgPhoto: "imgphoto/psitaco2.webp",
  },
  {
    name: "Pachycephalosaurus",
    common: "Paquicefalossauro",
    path: [
      "Ornithischia",
      "Marginocephalia",
      "Pachycephalosauria",
      "Pachycephalosauridae",
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 5,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/pachycelaphosaurus.png",
    imgPhoto: "imgphoto/pachycephalosaurus2.webp",
  },
  {
    name: "Stygimoloch",
    common: "Estigimoloque",
    path: [
      "Ornithischia",
      "Marginocephalia",
      "Pachycephalosauria",
      "Pachycephalosauridae",
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 3,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/estygimoloch.webp",
    imgPhoto: "imgphoto/stygmoloch2.webp",
  },
  {
    name: "Albertaceratops",
    common: "Albertacerátops",
    path: [
     "Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 6,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/Albertaceratops.jpg",
    imgPhoto: "imgphoto/alberta2.png",
  },
  {
    name: "Albertosaurus",
    common: "Albertossauro",
    path: [
      "Saurischia", "Theropoda", "Coelurosauria", "Tyrannosauridae"
    ],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 3,
    loco: "Bípede",
    region: "América do Norte",
    imgClassic: "img/alberto.webp", 
    imgPhoto: "imgphoto/alberto2.jpg",
  },
  {
    name: "Archelon",
    common: "Archelon",
    path: [
      "Testudines", "Cryptodira", "Chelonioidea", "Protostegidae"
      
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 4,
    loco: "Aquático",
    region: "América do Norte",
    imgClassic: "img/archelon.webp",
    imgPhoto: "imgphoto/archelon2.jpg",
  },
  {
    name: "Beipiasaurus",
    common: "Beipiassauro", 
    path: [
      "Saurischia", "Theropoda", "Coelurosauria", "Therizinosauridae"
    ],
    period: "Cretáceo",
    diet: "Carnívoro" ,
    size: 2,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/beipiasaurus.webp",
    imgPhoto: "imgphoto/Bipiasaurus2.jpg",
  },
  {
    name: "Concavenator",
    common: "Concavenator",
    path: [
      "Saurischia", "Theropoda", "Carnosauria", "Carcharodontosauridae"
    ],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 4,
    loco: "Bípede",
    region: "Europa",
    imgClassic: "img/concavenator.jpg",
    imgPhoto: "imgphoto/concavenator2.webp" ,
  },
  {
    name: "Deinosuchus",
    common: "Deinosuco",
    
    path: [
      "Crocodylia", "Eusuchia", "Alligatoroidea", "Alligatoridae"
    ],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 10,
    loco: "Aquático",
    region: "América do Norte",
    imgClassic: "img/deino.webp",
    imgPhoto: "imgphoto/deinos2.jpg",
  },
  {
    name: "Diabloceratops",
    common: "Diablocerátops",
    path: [
      "Ornithischia", "Marginocephalia", "Ceratopsia", "Ceratopsidae"
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 5,
    loco: "Quadrúpede",
    region: "América do Norte",
    imgClassic: "img/diablo.jpg",
    imgPhoto: "imgphoto/diablo2.jpg",
  },
   
  ,
  {
    name: "Elamosaurus",
    common: "Elamossauro",
  
    path: [
      "Sauropterygia", "Plesiosauria", "Plesiosauroidea", "Elasmosauridae"
    ],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 14,
    loco: "Aquático",
    region: "América do Norte",
    imgClassic: "img/Elasmossauro.webp",
    imgPhoto: "imgphoto/elasmossauro.webp",
  },
  {
    name: "ichthyvonator",
    common: "Icthyvonator",
    
    path: [
      "Saurischia","Theropoda","Spinosauridae"
    ],
    period: "Cretáceo",
    diet: "Herbívoro",
    size: 10,
    loco: "Bípede",
    region: "Ásia",
    imgClassic: "img/ichty.webp",
    imgPhoto: "imgphoto/ichty2.jpg",
  },
  {
    name: "Kronosaurus",
    common: "Kronossauro",
    
    path: [
      "Sauropterygia", "Plesiosauria", "Pliosauroidae" 
    ],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 10,
    loco: "Aquático",
    region: "América do Sul",
    imgClassic: "img/img/kronosaurus.png",
    imgPhoto: "imgphoto/kronossauro2.webp",
  },
  {
    name: "Mosasaurus",
    common: "Mossassauro",
    
    path: [
      "Squamata", "Anguimorpha", "Mosasauroidea", "Mosasauridae"
    ],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 11,
    loco: "Aquático",
    region: "Europa",
    imgClassic: "img/img/mosassauro.webp",
    imgPhoto: "imgphoto/mosassauro2.jpeg",
  },
  {
    name: "Sarcosuchus",
    common: "Sarcosuco",
    path: [
      "Crocodylia", "Eusuchia", "Notosuchia", "Peirosauridae"
    ],
    period: "Cretáceo",
    diet: "Carnívoro",
    size: 3,
    loco: "Aquático ",
    region: "América do Sul",
    imgClassic: "img/sarcosuchus.webpp",
    imgPhoto: "img/sarcosuchus.webpp",
  },
];
